# -*- coding: utf-8 -*-
import sys

from urllib.request import urlopen
from urllib.request import Request
from urllib.request import urlretrieve
import datetime
import json
import math
import argparse
import os

def get_results(url,headers):
    try:
        req =  Request(url,headers=headers)
        response = urlopen(req).read()
        results = json.loads(response.decode())
        return results
    except:
        return []

def main():
    token = ""
    owner = "Azure"
    name = "terraform-azurerm-compute"
    parser = argparse.ArgumentParser()
    parser.add_argument('--token', type=str, default=token, help='(Required) Authentication token generated by github account')
    parser.add_argument('--owner', type=str, default=owner, help='(Required) Define target repository owner.')
    parser.add_argument('--name', type=str, default=name, help="(Required) Define target repository name.")
    args = parser.parse_args()

    if args.token:
        token = args.token
    if args.owner:
        owner = args.owner
    if args.name:
        name = args.name

    ########################################## Main #########################################
    headers = {'User-Agent': 'Mozilla/5.0',
            'Authorization': 'token %s'%token,
            'Content-Type': 'application/json',
            'Accept': 'application/json'
    }
    
    url = 'https://api.github.com/repos/%s/%s/labels'%(owner,name)
    results = get_results(url, headers)
    labelToAuthor = "labelToAuthor: {\n"    

    for item in results:
        labelToAuthor += "  \"%s\": []\n"%item["name"]
    labelToAuthor +="}"

    with open('autoAssignees.yml', 'w') as f:
        f.write(labelToAuthor) 
    f.close()   

if __name__ == '__main__':
    main()